-- calendar-service baseline schema (PostgreSQL).
-- Lives in its own `calendar` schema inside the shared Postgres DB (see application.yml),
-- isolated from workspace-service's `public` schema and flyway history.

CREATE TABLE calendar_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    workspace_id BIGINT      NOT NULL,
    title        TEXT        NOT NULL,
    description  TEXT,
    start_time   TIMESTAMPTZ NOT NULL,
    end_time     TIMESTAMPTZ NOT NULL,
    busy         BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Owner + range lookups (list a user's events in a window; find a user's current event).
CREATE INDEX idx_calendar_event_owner  ON calendar_event (user_id, workspace_id);
-- Scheduler scan: busy events whose window contains "now", across all users.
CREATE INDEX idx_calendar_event_window ON calendar_event (start_time, end_time) WHERE busy;
