-- workspace-service baseline schema (normalized to BCNF — see DATABASE.md)
-- PostgreSQL. Enum domains enforced with CHECK constraints; app maps via @Enumerated(STRING).

CREATE TABLE workspace (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT        NOT NULL,
    slug             TEXT        NOT NULL UNIQUE,
    owner_id         BIGINT      NOT NULL,
    description      TEXT,
    logo_url         TEXT,
    status           VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'ARCHIVED', 'SUSPENDED')),
    visibility       VARCHAR(20) NOT NULL CHECK (visibility IN ('INVITE_ONLY')),
    invite_token     UUID        UNIQUE,
    default_timezone TEXT        NOT NULL,
    tile_size        INT         NOT NULL,
    map_width        INT         NOT NULL,
    map_height       INT         NOT NULL,
    map_geometry     JSONB,
    layout_version   BIGINT      NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE team (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT      NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    name         TEXT        NOT NULL,
    description  TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, name)
);

CREATE TABLE tileset (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    name         TEXT   NOT NULL,
    image_url    TEXT   NOT NULL,
    first_gid    INT    NOT NULL,
    tile_width   INT    NOT NULL,
    tile_height  INT    NOT NULL,
    columns      INT    NOT NULL,
    tile_count   INT    NOT NULL,
    UNIQUE (workspace_id, first_gid)
);

CREATE TABLE map_layer (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT  NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    name         TEXT    NOT NULL,
    layer_index  INT     NOT NULL,
    collides     BOOLEAN NOT NULL DEFAULT FALSE,
    data         JSONB   NOT NULL,
    UNIQUE (workspace_id, layer_index)
);

CREATE TABLE zone (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id     BIGINT      NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    type             VARCHAR(20) NOT NULL CHECK (type IN ('MEETING_ROOM', 'FOCUS_AREA', 'SOCIAL', 'TEAM', 'OPEN')),
    name             TEXT        NOT NULL,
    x                INT         NOT NULL,
    y                INT         NOT NULL,
    width            INT         NOT NULL,
    height           INT         NOT NULL,
    voice_room_id    TEXT        UNIQUE,
    proximity_radius INT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE spawn_point (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT  NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    x            INT     NOT NULL,
    y            INT     NOT NULL,
    label        TEXT,
    is_default   BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE desk (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL,
    workspace_id       BIGINT      NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    full_name          TEXT,
    nick_name          TEXT,
    title              TEXT,
    work_email         TEXT,
    phone              TEXT,
    personal_image_url TEXT,
    avatar_character   VARCHAR(20) NOT NULL CHECK (avatar_character IN ('ADAM', 'ASH', 'LUCY', 'NANCY')),
    timezone           TEXT,
    status             VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'AWAY', 'DO_NOT_DISTURB', 'FOCUS_MODE', 'CUSTOM')),
    status_emoji       TEXT,
    status_custom_text TEXT,
    position_x         INT         NOT NULL DEFAULT 0,
    position_y         INT         NOT NULL DEFAULT 0,
    is_online          BOOLEAN     NOT NULL DEFAULT FALSE,
    last_seen_at       TIMESTAMPTZ,
    role               VARCHAR(20) NOT NULL CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'GUEST')),
    bio                TEXT,
    team_id            BIGINT      REFERENCES team (id) ON DELETE SET NULL,
    invite_status      VARCHAR(20) NOT NULL CHECK (invite_status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED')),
    invited_by         BIGINT,
    is_active          BOOLEAN     NOT NULL DEFAULT TRUE,
    joined_at          TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, workspace_id)
);

CREATE TABLE desk_link (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desk_id BIGINT NOT NULL REFERENCES desk (id) ON DELETE CASCADE,
    url     TEXT   NOT NULL,
    UNIQUE (desk_id, url)
);

CREATE TABLE desk_widget (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desk_id  BIGINT      NOT NULL REFERENCES desk (id) ON DELETE CASCADE,
    type     VARCHAR(40) NOT NULL,
    label    TEXT,
    position INT         NOT NULL,
    config   JSONB,
    UNIQUE (desk_id, position)
);

CREATE TABLE map_object (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT      NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    type         VARCHAR(20) NOT NULL CHECK (type IN ('COMPUTER', 'WHITEBOARD')),
    label        TEXT,
    position_x   INT         NOT NULL,
    position_y   INT         NOT NULL,
    room_id      TEXT        NOT NULL UNIQUE,
    capacity     INT         NOT NULL DEFAULT 1,
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE workspace_invitation (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  BIGINT      NOT NULL REFERENCES workspace (id) ON DELETE CASCADE,
    invited_email TEXT        NOT NULL,
    invited_by    BIGINT      NOT NULL,
    token         UUID        NOT NULL UNIQUE,
    role          VARCHAR(20) NOT NULL CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'GUEST')),
    status        VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED')),
    expires_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes (beyond PK / UNIQUE)
CREATE INDEX idx_team_workspace        ON team (workspace_id);
CREATE INDEX idx_tileset_workspace     ON tileset (workspace_id);
CREATE INDEX idx_map_layer_workspace   ON map_layer (workspace_id);
CREATE INDEX idx_zone_workspace        ON zone (workspace_id);
CREATE INDEX idx_spawn_point_workspace ON spawn_point (workspace_id);
CREATE INDEX idx_desk_workspace_active ON desk (workspace_id) WHERE is_active;
CREATE INDEX idx_map_object_ws_active  ON map_object (workspace_id) WHERE is_active;
CREATE INDEX idx_invitation_ws_status  ON workspace_invitation (workspace_id, status);

-- No duplicate live invites for the same email in a workspace.
CREATE UNIQUE INDEX uq_invitation_pending
    ON workspace_invitation (workspace_id, invited_email) WHERE status = 'PENDING';
