-- tasks-service baseline schema (PostgreSQL).
-- Lives in its own `tasks` schema inside the shared Postgres DB (see application.yml),
-- isolated from the other services' schemas and flyway history.

CREATE TABLE task (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Per-workspace sequential number (assigned as max(task_number)+1 on create); powers
    -- @task-number chat mentions. Unique within a workspace via the constraint below.
    task_number      BIGINT      NOT NULL,
    workspace_id     BIGINT      NOT NULL,
    title            TEXT        NOT NULL,
    description      TEXT,
    -- TODO | IN_PROGRESS | COMPLETE
    status           VARCHAR(20) NOT NULL DEFAULT 'TODO',
    -- LOW | NORMAL | HIGH
    priority         VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    due_date         TIMESTAMPTZ,
    assignee_user_id BIGINT,
    created_by       BIGINT      NOT NULL,
    reminder_minutes INTEGER,
    reminder_sent_at TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_task_workspace_number UNIQUE (workspace_id, task_number)
);

-- List/board queries scoped to a workspace.
CREATE INDEX idx_task_workspace ON task (workspace_id);
-- "My tasks" and per-assignee board columns.
CREATE INDEX idx_task_workspace_assignee ON task (workspace_id, assignee_user_id);
-- Reminder scan: pending reminders with a future due date.
CREATE INDEX idx_task_reminder ON task (due_date)
    WHERE reminder_sent_at IS NULL AND reminder_minutes IS NOT NULL;
