-- Team Spaces: a workspace has one or more spaces; each space has an explicit member set
-- (who can see it) and owns its own tasks. Lives in the `tasks` schema alongside `task`.

CREATE TABLE task_space (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT      NOT NULL,
    name         VARCHAR(120) NOT NULL,
    created_by   BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_task_space_workspace ON task_space (workspace_id);

-- Membership: which users can access a space.
CREATE TABLE task_space_member (
    space_id BIGINT NOT NULL REFERENCES task_space (id) ON DELETE CASCADE,
    user_id  BIGINT NOT NULL,
    PRIMARY KEY (space_id, user_id)
);
CREATE INDEX idx_task_space_member_user ON task_space_member (user_id);

-- Tasks now belong to a space.
ALTER TABLE task ADD COLUMN space_id BIGINT;

-- Backfill: give every workspace that already has tasks a default "General" space,
-- move its tasks into it, and seed membership with the tasks' creators and assignees.
INSERT INTO task_space (workspace_id, name, created_by, created_at, updated_at)
SELECT workspace_id, 'General', MIN(created_by), now(), now()
FROM task
GROUP BY workspace_id;

UPDATE task t
SET space_id = s.id
FROM task_space s
WHERE s.workspace_id = t.workspace_id AND s.name = 'General';

INSERT INTO task_space_member (space_id, user_id)
SELECT DISTINCT s.id, u.uid
FROM task_space s
JOIN task t ON t.workspace_id = s.workspace_id
CROSS JOIN LATERAL (VALUES (t.created_by), (t.assignee_user_id)) AS u(uid)
WHERE u.uid IS NOT NULL
ON CONFLICT DO NOTHING;

-- Every task must now live in a space.
ALTER TABLE task ALTER COLUMN space_id SET NOT NULL;
CREATE INDEX idx_task_space ON task (space_id);
CREATE INDEX idx_task_space_status ON task (space_id, status);
